# Generated by Django 4.0.6 on 2022-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('city', models.CharField(max_length=30, verbose_name='شهز')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='واتس اپ')),
                ('telegram', models.CharField(max_length=100, verbose_name='تلگرام')),
                ('instagram', models.CharField(max_length=100, verbose_name='اینستاگرام')),
            ],
        ),
    ]
